### PR TITLE
Signal wrapper

### LINKED ISSUE #57: do we have time to react if we get a cancellation or other signal?
ideal situation if we get a signal around cancellation from slurm or aws (eg spot instance) we should both start cleaning up + drop metadata into the output dir that it was killed.

For further internal discussion but starting issue now

```
❯ cat 1000_17805.out
Running model: "/cluster-data/user-homes/devin/nonmem-scratch/1000.mod"
slurmstepd: error: *** JOB 17805 ON cpu4mem16gb-dy-c7i-2xlarge-1 CANCELLED AT 2025-11-02T13:03:07 ***
```

### PR DESCRIPTION
**Pull request by Keats**
Closes #57

### CODE REVIEW

File: components/nonmem/src/signal_wrapper.rs [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+    // Spawn child process
+    let mut child = command.spawn()?;
+
+    // Simple main loop: check for signals and child completion
+    loop {
+        // Check for signals first (this makes Ctrl+C responsive)
+        if sigint_received.load(Ordering::Relaxed) {
+            log::info!("SIGINT detected, terminating process");
+            let _ = child.kill(); // Kill child process first
+            write_termination_file(output_dir, "SIGINT", "User interruption (Ctrl+C)")?;
```
Comment (dpastoor) [inline components/nonmem/src/signal_wrapper.rs]: if any of these write_termination_file ops fail, we'd never exit with the proper exit code, would it be better to swallow this error, printing an error message at least but then exiting
